# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  host: db

# if running on localhost set password of postgres user accordingly
#  host: localhost
#  password: postgres

development:
  <<: *default
  database: ol_development

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: ol_production
  username: ol
  password: <%= ENV['OL_DATABASE_PASSWORD'] %>
